# This is the docker-compose file meant purely for the local development environment. Note that the real
# production environment will have a different configuration.
services:
    db:
        image: "postgres:18"
        volumes:
            - ./local-postgres-init:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
