# This is the docker-compose file meant purely for the local development environment. Note that the real
# production environment will have a different configuration.
services:
  db:
    image: "postgres:18"
    volumes:
      - ./local-postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    ports:
      - 9090:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - 'start-dev'
  keycloak-config:
    image: adorsys/keycloak-config-cli:latest-26
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: http://keycloak:8080/
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "15s"
      IMPORT_FILES_LOCATIONS: "/config/*"
    volumes:
      - ./keycloak/realm-config.json:/config/realm-config.json:ro
volumes:
  keycloak_data: